services:
  db:
    build: ./mizdooni-db
    restart: always
    networks:
      - mizdooni
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mizdooni-admin
      MYSQL_PASSWORD: admin56@Mizdooni
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      start_period: 0s
      interval: 10s
      retries: 20
      test: ["CMD-SHELL", "/check_db.sh"]
    stdin_open: true
    tty: true

  app:
    build: ./mizdooni-backend
    networks:
      - mizdooni
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mizdooni
      SPRING_DATASOURCE_USERNAME: mizdooni-admin
      SPRING_DATASOURCE_PASSWORD: admin56@Mizdooni
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  web:
    build: ./mizdooni-frontend
    networks:
      - mizdooni
    depends_on:
      app:
        condition: service_healthy
    ports:
      - 80:80
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:80/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.db

networks:
  mizdooni:
    driver: bridge
